### PR TITLE
Add strict typings via TypeScript

### PR DESCRIPTION
**Pull request by tgriesser**
Hey @koskimas not sure if this is something you're interested in, but as I'm preparing a path forward for knex to begin to use TypeScript for things I was looking at what dependencies have type definitions via DefinitelyTyped. As tarn didn't I thought I'd make a PR to add them, but then instead took a few minutes and added types to the whole module.

As you can probably tell from the diff, there aren't any implementation changes, just a few things around the emitted `require`'s. If you'd rather keep things simpler in pure JS with no build step, I can just consolidate all of the type definitions into a single `d.ts` and reopen with a PR for that.

### CODE REVIEW

**Comment by koskimas** [comment]
@tgriesser Absolutely interested, thank you! Tarn was basically created for knex and I think it should follow the direction knex takes. I'll review and merge this a bit later if that's okay?

**Comment by tgriesser** [comment]
Sure thing, no rush at all.

**Comment by tgriesser** [comment]
Up to you if you want to `.gitignore` `lib`, I mostly kept it in here so you could review the diff of the output.

**Comment by koskimas** [comment]
@tgriesser Feel free to push straight to master in the future.

**Pull request merged**
