### PR TITLE
Add linting

### PR DESCRIPTION
**Pull request by kibertoad**
Update dependencies

### CODE REVIEW

**Comment by elhigu** [comment]
So is tslint or eslint nowadays correct choice for typescript? I have not been following that at all 😅

**Comment by kibertoad** [comment]
@elhigu ESLint: https://medium.com/palantir/tslint-in-2019-1a144c2317a9

**Comment by kibertoad** [comment]
@elhigu lib file update removed

**Comment by elhigu** [comment]
Thanks!

**Pull request merged**
