### PR TITLE
Added changelog and updated package.json with next revision

### PR DESCRIPTION
**Pull request by elhigu**
I'm not sure if I have rights to publish new versions in npm (didn't try).

### CODE REVIEW

**Comment by elhigu** [comment]
Whats the policy with package-lock.json file? Should it be included in every PR or just for releases or something? I mean that if it is in every PR there will be conflicts.

**Comment by koskimas** [comment]
I don't think there will be that many PR's here. Whichever works.

**Comment by elhigu** [comment]
Looks like I had npm publish rights after all 🙂

 1.1.5 is now tagged and out 🎉

**Comment by koskimas** [comment]
Thanks!

**Pull request merged**
