### PR TITLE
Do not commit generated files

### PR DESCRIPTION
**Pull request by kibertoad**
There doesn't seem to be much sense to commit generated files to the repo, as these are intended to be dynamically regenerated on every change anyway, and there is already a prepublish hook for that.
This also bumps TypeScript version.

### CODE REVIEW

**Comment by kibertoad** [comment]
Apparently CI never executed any tests 😅

**Comment by elhigu** [comment]
It has been running tests at least according to travis. IIRC if `script:` is not declared it is expected to be `npm run test` by default  for nodejs setups.

I agree that  with this library having built files in repo is not really necessary (though they are useful in some special case where people are using link to certain commit in github in their package.json instead of released version).

Also if those files would be committed at the same time when npm release is done, they would be nice to have to see exact built version files of each release... but still not really necessary.

**Comment by kibertoad** [comment]
@koskimas What's your opinion?

**Comment by elhigu** [comment]
I think we can remove those... If we regret that someday it will be easy to add them back :)

**Comment by elhigu** [comment]
Thanks!

**Pull request merged**
